CREATE TABLE ModRequest (
    SenderId INTEGER NOT NULL,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Seen INTEGER CHECK (Seen IN (1, 0)) DEFAULT 0,
    FOREIGN KEY (SenderId) REFERENCES User(ID) ON DELETE CASCADE
);

